# Generated by Django 4.0.5 on 2022-06-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateField(auto_now=True)),
                ('phone', models.CharField(max_length=8)),
                ('is_staff', models.BooleanField(default=True)),
                ('last_login', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
