# Generated by Django 4.0.5 on 2022-06-28 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='last_login',
            field=models.CharField(max_length=50),
        ),
    ]
