# Generated by Django 4.0.5 on 2022-08-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Acounts', '0002_alter_acount_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acount',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
