# Generated by Django 4.0.5 on 2022-06-21 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='stuff',
            fields=[
                ('reference', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date_found', models.DateField()),
                ('date_created', models.DateField()),
                ('User', models.CharField(max_length=15, unique=True)),
                ('description', models.CharField(blank=True, max_length=15)),
                ('place', models.CharField(blank=True, max_length=15)),
                ('categroy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Category.category')),
            ],
        ),
    ]
