# Generated by Django 4.0.5 on 2022-06-21 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='reference',
            field=models.CharField(max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
