# Generated by Django 4.0.5 on 2022-07-01 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0003_alter_stuff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='image_four',
            field=models.ImageField(null=True, upload_to='stuff/imgs'),
        ),
        migrations.AddField(
            model_name='stuff',
            name='image_one',
            field=models.ImageField(null=True, upload_to='stuff/imgs'),
        ),
        migrations.AddField(
            model_name='stuff',
            name='image_three',
            field=models.ImageField(null=True, upload_to='stuff/imgs'),
        ),
        migrations.AddField(
            model_name='stuff',
            name='image_two',
            field=models.ImageField(null=True, upload_to='stuff/imgs'),
        ),
    ]
