# Generated by Django 4.0.5 on 2022-07-03 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0004_stuff_image_four_stuff_image_one_stuff_image_three_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stuff',
            name='image_four',
        ),
        migrations.RemoveField(
            model_name='stuff',
            name='image_three',
        ),
        migrations.RemoveField(
            model_name='stuff',
            name='image_two',
        ),
        migrations.AlterField(
            model_name='stuff',
            name='image_one',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
