# Generated by Django 4.0.5 on 2022-08-04 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0008_stuff_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='preview_image',
            field=models.ImageField(default='stuff/imgs/472038.jpg', upload_to='imgs'),
        ),
    ]
