# Generated by Django 4.0.5 on 2022-08-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0009_alter_stuff_preview_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.IntegerField(default=25),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.IntegerField(default=36),
        ),
    ]
