# Generated by Django 4.0.5 on 2022-06-21 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stuff', '0002_alter_stuff_reference'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AddField(
            model_name='image',
            name='reff',
            field=models.CharField(default='image', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='image',
            name='stuff',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='stuff.stuff'),
            preserve_default=False,
        ),
    ]
